NUM_LABELED = 3958

# learning rates
LR_FULLY_SUPERVISED = 0.001
LR_PRETEXT = 0.001
LR_DOWNSTREAM_TRANSFER = 0.01
LR_DOWNSTREAM_FINE_TUNING = 0.0001

# batch sizes
BATCH_FULLY_SUPERVISED = 16
BATCH_PRETEXT = 16
BATCH_DOWNSTREAM_TRANSFER = 16
BATCH_DOWNSTREAM_FINE_TUNING = 16

# epochs
EPOCH_FULLY_SUPERVISED = 25
EPOCH_PRETEXT = 10
EPOCH_DOWNSTREAM_TRANSFER = 15
EPOCH_DOWNSTREAM_FINE_TUNING = 10

